name: Deploy Kubernetes Resources

on:
  push:
    branches:
      - main

jobs:
  setup-cluster:
    name: Setup EKS Cluster
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-2
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/v0.149.0/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Create EKS cluster
        run: |
          set -e
          eksctl create cluster -f clusterConfig.yml

      - name: Cleanup Failed Cluster
        if: failure() # Only run if the previous steps failed
        run: |
          eksctl delete cluster --region=${{ env.AWS_REGION }} --name=Pro88-cluster

      - name: Create kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Configure kubectl
        run: |
          set -e
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name Pro88-cluster

      - name: Validate EKS cluster
        run: |
          eksctl get cluster --region ${{ env.AWS_REGION }}
          kubectl get nodes
        
  deploy-resources:
    name: Deploy Kubernetes Resources
    needs: setup-cluster
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-2
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Validate Kubernetes YAML Files
        run: |
          cd Deploy
          kubectl apply --dry-run=client -f nginx-deploy.yml
          kubectl apply --dry-run=client -f nginx-service.yml
          kubectl apply --dry-run=client -f prom-deploy.yml
          kubectl apply --dry-run=client -f prom-service.yml
          kubectl apply --dry-run=client -f node-exporter-deploy.yml
          kubectl apply --dry-run=client -f node-exporter-svc.yml
  
      - name: Apply Nginx Deployment and Service
        run: |
          set -e
          cd Deploy
          kubectl apply -f nginx-deploy.yml 
          kubectl apply -f nginx-service.yml
          
      - name: Apply Prometheus Deployment and Service
        run: |
          set -e
          cd Deploy
          kubectl apply -f prom-deploy.yml 
          kubectl apply -f prom-service.yml 
          
      - name: Apply Prometheus Node Exporter DaemonSet and Service
        run: |
          set -e
          cd Deploy
          kubectl apply -f node-exporter-deploy.yml 
          kubectl apply -f node-exporter-svc.yml 
